spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      show-sql: true
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

telegram:
  bot:
    name: dworfsgamebot
    token: 7029187576:AAGGXeneTAw_UVy1RkUulrQqUeTd9dB0c6w

admin:
  chatId: 1717946938
#  chatId: 777166751

server:
  port: 80

