spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dwarfs
    username: root
    password: 336Abc$420#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.xml

telegram:
  bot:
    name: dworfsgamebot
    token: 7029187576:AAGGXeneTAw_UVy1RkUulrQqUeTd9dB0c6w

server:
  port: 8080

