package com.sailordev.dvorfsgamebot.telegram.dto;

public enum UserState {
    SLEEP,
    AWAIT_START,
    AWAIT_MESSAGE_TO_ADMIN,
    AWAIT_ADMINS_RESPONSE,
    AWAIT_USER_SELECTION,
    AWAIT_SET_EVENT_DATE,
    AWAIT_SET_NAME_OR_DESCRIPTION_EVENT,
    AWAIT_REGISTRATION,
    AWAIT_RESPONSE_TO_USER,
    AWAIT_SELECT_ACTION,
    AWAIT_SEND_MESSAGE_TO_USER,
    AWAIT_SET_KEYBOARD, BAN
}
